import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import Header from "./components/header";
import "./globals.css";

const comforter = Comforter({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={comforter.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
